vich_uploader:
    db_driver: orm

    mappings:
        photos:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        documents:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
